### ISSUE TITLE
Interface is confusing

### ISSUE THREAD

**Issue by glasserc** [mozilla/signing-clients#25]
The `make_signed` method writes a signature to an XPI. That signature was computed over some manifest, which `make_signed` also writes to an XPI. However, `make_signed` cannot know what manifest was signed. Instead, it always writes `self.signatures`. `self.signatures` is computed according to the constructor parameter `omit_signature_sections` and `extra_newlines`.

There are a lot of confusing parts to this interface:

- When someone uses a `JarExtractor`, they have to know what kind of signatures they are going to compute. Because the signing process we follow is not very well documented anywhere (it's "basically the same as JAR signing"), a user will probably cargo-cult `omit_signature_sections` and `extra_newlines` without knowing what they do.
- Worse yet, the default values are probably wrong. Mozilla-signed XPIs *always* omit signature sections, yet the default is false.
- `omit_signature_sections` isn't even really necessary because `JarExtractor` has two properties, `self.signature` (which only ever has the "header", as though with `omit_signature_sections` as True), and `self.signatures` (which a naive user might assume to always have all the signature sections). Calling code can specify what they want.
- `make_signed` cannot know what signature to write. Rather than implicitly using `self.signatures`, which must be customized by an underdocumented constructor argument, perhaps it should take the content that was signed as a method argument.

**Comment by EnTeQuAk** [comment]
Indeed, I agree with you and the confusing interface. I only recently took over signing-clients and didn't have the time to change too many things about it so my comments are basically agreements with you :)

> Worse yet, the default values are probably wrong. Mozilla-signed XPIs always omit signature sections, yet the default is false.

And everywhere we are using it it's set to `True` afair so this should be changed.

I think I simply agree on the other things, can we get this into signing-clients or what's the plan with https://github.com/mozilla-services/sign-xpi-lib in the long term? I don't know who else is using `signing-clients` but I personally would like to avoid us maintaining two projects that do more or less the same but look different.

**Comment by EnTeQuAk** [comment]
I assume this can be closed mostly?

**Comment by glasserc** [comment]
Yes, all of the criticisms are fixed now. `omit_signature_sections` is gone and `make_signed` requires a `signature` argument. Thanks!
