### ISSUE TITLE
add ability to re-sign an addon without duplicating the META-INF files

### ISSUE THREAD

**Issue by magopian** [mozilla/signing-clients#9]
At the moment, if we `make_signed()` more than once, the `META-INF` files are duplicated.

We need to resign add-ons in some cases, when going from preliminary to fully reviewed for example.

I believe adding a filter on [this line](https://github.com/mozilla/signing-clients/blob/master/signing_clients/apps.py#L294) would work.

**Comment by rtilder** [comment]
I think this should do it but would like to test with the FirefoxOS privileged app signing before merging to master.

https://github.com/mozilla/signing-clients/commit/d12c2d6cd31a3fab0d35a697b3c51517e6b96e37

**Comment by magopian** [comment]
Tested on olympia, seems to be working as expected. I could re-sign an already signed xpi, and the `META-INF` files were not duplicated. Thanks!

**Comment by glasserc** [comment]
I think this can be closed now?
